//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCarDump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InSiteLogin
    {
        public int Id { get; set; }
        public int userid { get; set; }
        public string md5hash { get; set; }
        public System.DateTime expirydate { get; set; }
    
        public virtual User User { get; set; }
    }
}
