//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCarDump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceHistory
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime SetTime { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
