//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCarDump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RawData { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price2 { get; set; }
    
        public virtual ServicesCategory ServicesCategory { get; set; }
        public override string ToString()
        {
            return Name;
        }
    }
}
