//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

[Serializable]
public partial class ServiceCategory
{
    public ServiceCategory()
    {
        this.SPServices = new HashSet<SPService>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public int ParentID { get; set; }
    public string Descriprion { get; set; }

    public virtual ICollection<SPService> SPServices { get; set; }

    public override string ToString()
    {
        return Name;
    }
}
