//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

[Serializable]
public partial class SPService
{
    public int Id { get; set; }
    public int CategoryID { get; set; }
    public string RawShort { get; set; }
    public string RawData { get; set; }

    public virtual ServiceCategory ServiceCategory { get; set; }
}
