//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCarDump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.InSiteLogins = new HashSet<InSiteLogin>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string FirstName { get; set; }
        public int PermissionID { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string Description { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual UserPermission UserPermission { get; set; }
        public virtual ICollection<InSiteLogin> InSiteLogins { get; set; }
    }
}
